version: '3.6'
services:
  app:
    build: .
    environment:
      - E_ACCOM_API_URL=https://demo.eaccom.net/api/v1/booking
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjU2ZmViYWVjYTJhMDAxM2Q1NjJlZiIsInVzZXJuYW1lIjoic3VwZXJ1c2VyIiwiZXhwIjoxNjkxNjQ3OTQ4LCJpYXQiOjE2ODM4NzE5NDh9.UtjGfwQbB2aRq9KERYcheyRQkSrX-EgpvPxVocDWJkk